apiVersion: v1
kind: Secret
metadata:
  name: frontend-secret
  namespace: frontend
  annotations:
    argocd.argoproj.io/sync-wave: "1"

type: Opaque

stringData:
  APP_NAME: Frontend
  APP_ENV: Production