apiVersion: v1
kind: Secret

metadata:
  name: backend-secret
  namespace: backend
  annotations:
    argocd.argoproj.io/sync-wave: "1"

type: Opaque

stringData:
  APP_NAME: Backend
  APP_ENV: Production