apiVersion: v1
kind: Service

metadata:
  name: backend-service
  namespace: backend
  annotations:
    argocd.argoproj.io/sync-wave: "3"

spec:
  selector:
    app: backend

  ports:
    - port: 80
      targetPort: 80

  type: NodePort