apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet

metadata:
  name: html-applicationset
  namespace: argocd

spec:
  generators:
    - list:
        elements:
          - appName: frontend
            namespace: frontend
            path: apps/frontend

          - appName: backend
            namespace: backend
            path: apps/backend

  template:
    metadata:
      name: '{{appName}}'

    spec:
      project: default

      source:
        repoURL: https://github.com/nagaraju-thota/html-gitops-demo.git
        targetRevision: main
        path: '{{path}}'

      destination:
        server: https://kubernetes.default.svc
        namespace: '{{namespace}}'

      syncPolicy:
        automated:
          prune: true
          selfHeal: true

        syncOptions:
          - CreateNamespace=true